apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanstore-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cleanstore-app
  template:
    metadata:
      labels:
        app: cleanstore-app
    spec:
      containers:
      - name: cleanstore-web
        image: ki3ani/cleanstore:latest
        ports:
        - containerPort: 8000
