version: '3.8'

services:
  web:
    build: .
    command: gunicorn your_project_name.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}

volumes:
  static_volume:
