version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=cleanstore.settings
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=staples
      - POSTGRES_USER=ken
      - POSTGRES_PASSWORD=invincible
