name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python manage.py test

    - name: Build Docker image
      run: docker build -t ki3ani/cleaningstore:latest .

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image to DockerHub
      run: docker push ki3ani/cleaningstore:latest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull ki3ani/cleaningstore:latest

    - name: Run Migrate and Collectstatic
      run: |
        docker run -e DATABASE_URL=${{ secrets.DATABASE_URL }} ki3ani/cleaningstore:latest sh -c "python manage.py migrate && python manage.py collectstatic --noinput"

    - name: Deploy to Railway
      uses: railwayapp/actions/deploy@v1.2
      with:
        projectId: ${{ secrets.RAILWAY_PROJECT_ID }}
        apiKey: ${{ secrets.RAILWAY_API_KEY }}
