name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AFRICAS_TALKING_USERNAME: ${{ secrets.AFRICAS_TALKING_USERNAME }}
      AFRICAS_TALKING_APIKEY: ${{ secrets.AFRICAS_TALKING_APIKEY }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Pull Docker images
        run: |
          docker pull ki3ani/cleanstore-web:latest
          docker pull postgres:latest

      - name: Run tests
        run: |
          docker-compose up -d
          docker-compose exec web python manage.py test
          docker-compose down

      - name: Migrate database
        run: |
          docker-compose run web python manage.py migrate

      - name: Collect static files
        run: |
          docker-compose run web python manage.py collectstatic --noinput

      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy
        run: eb deploy Tintin-env
