name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AFRICAS_TALKING_USERNAME: ${{ secrets.AFRICAS_TALKING_USERNAME }}
      AFRICAS_TALKING_APIKEY: ${{ secrets.AFRICAS_TALKING_APIKEY }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test with Docker Compose
        run: |
          docker compose up -d
          docker compose exec web python manage.py test
          docker compose down

      - name: Migrate database
        run: |
          docker compose up -d
          docker compose exec web python manage.py migrate
          docker compose down

      - name: Collect static files
        run: |
          docker compose up -d
          docker compose exec web python manage.py collectstatic --noinput
          docker compose down

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker tag your-docker-compose-service-name "${{ secrets.DOCKERHUB_USERNAME }}/your-docker-compose-service-name:latest"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/your-docker-compose-service-name:latest"

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy
        run: eb deploy Tintin-env
