name: Django CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker compose build
        working-directory: ./cleanstore

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker compose run \
            -e AFRICAS_TALKING_APIKEY=${{ secrets.AFRICAS_TALKING_APIKEY }} \
            -e AFRICAS_TALKING_USERNAME=${{ secrets.AFRICAS_TALKING_USERNAME }} \
            -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            -e GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }} \
            web python manage.py test
        working-directory: ./cleanstore

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python and AWS credentials, and upgrade pip
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install AWS Elastic Beanstalk CLI
        run: |
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS_REGION: ${{ secrets.AWS_REGION }}"
          pip install --upgrade pip
          pip install awsebcli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Debug SSH Key
        run: ls -l ~/.ssh || true  # Ignore failure if .ssh doesn't exist

      - name: Set AWS_EB_CLI_HOME
        run: echo "AWS_EB_CLI_HOME=${HOME}/.ssh" >> $GITHUB_ENV

      - name: Create ~/.ssh directory
        run: mkdir -p ~/.ssh

      - name: Create known_hosts file
        run: touch ~/.ssh/known_hosts

      - name: Debug known_hosts before
        run: cat ~/.ssh/known_hosts

      - name: Add Elastic Beanstalk host key to known_hosts
        run: ssh-keyscan -H cleanstoreobv-env.eba-pkj7kp8j.us-east-2.elasticbeanstalk.com >> ~/.ssh/known_hosts

      - name: Debug known_hosts after
        run: cat ~/.ssh/known_hosts

      - name: Set correct permissions for SSH directory
        run: chmod 700 ~/.ssh

      - name: Set correct permissions for SSH config file
        run: chmod 600 ~/.ssh/config

      - name: Debug SSH Config
        run: cat ~/.ssh/config

      - name: Add SSH private key to agent
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY_AWSEB }}" > ~/.ssh/aws-eb
          chmod 600 ~/.ssh/aws-eb
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/aws-eb

      - name: Run migrations before deployment
        run: docker-compose run -e DJANGO_SETTINGS_MODULE=your_project.settings web python manage.py migrate
        working-directory: ./cleanstore

      - name: Collect static files before deployment
        run: docker-compose run -e DJANGO_SETTINGS_MODULE=your_project.settings web python manage.py collectstatic --noinput
        working-directory: ./cleanstore

      - name: Initialize Elastic Beanstalk CLI
        run: eb init -r ${{ secrets.AWS_REGION }} -p docker Cleanstoreobv-env

      - name: Deploy to Elastic Beanstalk
        run: eb deploy Cleanstoreobv-env --label app-240227_021624914308 --staged

      - name: Run migrations and collect static files after deployment
        run: |
          eb ssh Cleanstoreobv-env --command "docker exec -it cleanstore_web_1 python manage.py migrate && docker exec -it cleanstore_web_1 python manage.py collectstatic --noinput"
